deepsource fixes [build]
pytrip/pytrip pull request #659
Opened 2021-12-16 16:56 UTC by michal367

fixes:
- Consider using in - PYL-R1714
- Unnecessary parentheses after keyword - PYL-C0325
- Inconsistent return statements - PYL-R1710
- Audit: Starting a process with a partial executable path - BAN-B607
- Possible shell injection via Paramiko call - BAN-B601
- Audit required: Use of eval - PYL-W0123
- Too many positional arguments in function call - PYL-E1121
- Missing argument in function call - PYL-E1120
- Unnecessary else / elif used after break - PYL-R1723
- Unnecessary elif / else block after continue - PYL-R1724
- Unnecessary else / elif used after return - PYL-R1705
- Unnecessary else/elif used after raise - PYL-R1720
- Loop variable used outside the loop - PYL-W0631
- Exception caught is very general - PYL-W0703
- Comparison with itself - PYL-R0124
- Argument redefined from local - PYL-R1704
- Re-definition found for builtin function - PYL-W0622
- Implicit enumerate calls found - PTC-W0060
- if statements can be merged - PTC-W0048
- Function/method with an empty body - PTC-W0049
- File opened without the with statement - PTC-W0010
- Unused variable found - PYL-W0612
- Dangerous default argument - PYL-W0102

2021-12-16 20:02 UTC, grzanka approved these changes
Looks OK

2021-12-16 20:06 UTC, grzanka commented
Fix as well this one:
![image](https://user-images.githubusercontent.com/7374733/146441775-84832dd9-f589-4384-9db6-d5bcc571dcde.png)

2021-12-17 03:13 UTC, Yoanka requested changes

2021-12-17 17:05 UTC, michal367 commented on pytrip/res/concave_tool.py
> +import math
I've moved import, added license comment at the beginning of the file and converted CRLF to LF.

2021-12-17 17:29 UTC, Yoanka approved these changes
Looks good to me.

2021-12-17 17:43 UTC, grzanka commented
@michal367 could you please squash-merge ?

2021-12-17 19:30 UTC, merged